parser: babel-eslint
extends:
  - eslint:recommended
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      semi: true
  eqeqeq:
    - error
    - always
